server {
    listen       80;
    listen  [::]:80;
    server_name  3.101.38.150;

    root   /usr/share/nginx/html;
    index  index.html;

    # Serve index.html for all unknown paths
    location / {
        try_files $uri /index.html;
    }

    # Error page for server errors
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

