events {
    worker_connections 1024; # Adjust this value based on expected traffic
}

http {
    server {
        listen 80;

        server_name 13.57.252.238; # Replace with your EC2 public IP or domain name

        # Serve the frontend
        location / {
            proxy_pass http://filmflicks-frontend:80; # Frontend service in Docker
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }

        # Proxy backend API requests
        location /api/ {
            proxy_pass http://filmflicks-backend:8080; # Backend service in Docker
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }
    }
}

